FROM nginx
# Overwrite the default.conf file which is in /etc/nginx/conf.d folder inside the nginx image with the the default.conf that we created in this project.
COPY ./default.conf /etc/nginx/conf.d/default.conf